name: build GPU

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_TESTS=ON
          make
      - name: Test
        run: |
          cd build
          ctest --output-on-failure .
