name: build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          chmod +x scripts/install_dependencies.sh
          scripts/install_dependencies.sh
          sudo apt install gcc-10 g++-10
      - name: Install drivers
        run: |
          chmod +x scripts/install_opencl_drivers.sh
          scripts/install_opencl_drivers.sh
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_TESTS=ON
          make
        env:
          CC: gcc-10
          CXX: g++-10

      - name: Test
        run: |
          cd build
          ctest --output-on-failure .