
name: build

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          chmod +x scripts/install_dependencies.sh
          scripts/install_dependencies.sh
      - name: Install drivers
        run: |
          chmod +x scripts/install_opencl_drivers.sh
          scripts/install_opencl_drivers.sh
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Test
        run: |
          cd build
          ctest --output-on-failure .
